[general]
import = [
  "alacritty.mac.toml",
  "alacritty.windows.toml",
  "alacritty.linux.toml",
]

[colors.primary]
background = "#000000"

[font]
size = 28

[font.normal]
style = "Medium"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold-Italic"

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
chars = "\u0000"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "Space"
mods = "Shift"
chars = "\u001b[32;2u"
