[font.normal]
family = "Terminus (TTF) for Windows"

[font.bold]
family = "Terminus (TTF) for Windows"

[font.italic]
family = "Terminus (TTF) for Windows"

[font.bold_italic]
family = "Terminus (TTF) for Windows"
